Repository naneun/todo-list, pull requests merged in 2022-04, with the labels that each got.

#5 [Jason] iOS 프로젝트 생성 및 .gitignore 추가
  .gitignore
  iOS/README.md
  iOS/todo-list/todo-list.xcodeproj/project.pbxproj
  iOS/todo-list/todo-list.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/todo-list/todo-list.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/todo-list/todo-list/AppDelegate.swift
  iOS/todo-list/todo-list/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/todo-list/todo-list/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/todo-list/todo-list/Resource/Assets.xcassets/Contents.json
  iOS/todo-list/todo-list/Resource/Base.lproj/LaunchScreen.storyboard
  iOS/todo-list/todo-list/Resource/Base.lproj/Main.storyboard
  iOS/todo-list/todo-list/SceneDelegate.swift
  iOS/todo-list/todo-list/ViewController/ViewController.swift
  iOS/todo-list/todo-list/configuration/Info.plist
  iOS/todo-list/todo-listTests/todo_listTests.swift
  iOS/todo-list/todo-listUITests/todo_listUITests.swift
  iOS/todo-list/todo-listUITests/todo_listUITestsLaunchTests.swift
Labels: iOS, COMMON

#11 [후] .github 설정 파일(템플릿) 작성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, COMMON

#10 [Riako] backend 프로젝트 폴더 생성 및 프로젝트 초기 구성
  backend/.gitignore
  backend/.gradle/7.1/dependencies-accessors/dependencies-accessors.lock
  backend/.gradle/7.1/dependencies-accessors/gc.properties
  backend/.gradle/7.1/executionHistory/executionHistory.bin
  backend/.gradle/7.1/executionHistory/executionHistory.lock
  backend/.gradle/7.1/fileChanges/last-build.bin
  backend/.gradle/7.1/fileHashes/fileHashes.bin
  backend/.gradle/7.1/fileHashes/fileHashes.lock
  backend/.gradle/7.1/gc.properties
  backend/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  backend/.gradle/buildOutputCleanup/cache.properties
  backend/.gradle/buildOutputCleanup/outputFiles.bin
  backend/.gradle/checksums/checksums.lock
  backend/.gradle/vcs-1/gc.properties
  backend/.idea/.gitignore
  backend/.idea/compiler.xml
  backend/.idea/gradle.xml
  backend/.idea/jarRepositories.xml
  backend/.idea/misc.xml
  backend/.idea/vcs.xml
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/hooria/todo/TodoApplication.java
  backend/src/main/java/com/hooria/todo/config/SwaggerConfig.java
  backend/src/main/java/com/hooria/todo/controller/MemberController.java
  backend/src/main/java/com/hooria/todo/domain/Member.java
  backend/src/main/java/com/hooria/todo/repository/MemberRepository.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/hooria/todo/DataSourceTest.java
  backend/src/test/java/com/hooria/todo/TodoApplicationTest.java
  backend/src/test/java/com/hooria/todo/repository/MemberRepositoryTest.java
  backend/src/test/resources/data.sql
  backend/src/test/resources/schema.sql
  backend/system.properties
Labels: BE

#12 [후] README.md 작성
  README.md
Labels: documentation, COMMON

#18 [Riako] 테스트 코드 TODO 처리 및 개선
  backend/src/main/java/com/hooria/todo/domain/Member.java
  backend/src/test/java/com/hooria/todo/repository/ActivityLogRepositoryTest.java
  backend/src/test/java/com/hooria/todo/repository/MemberRepositoryTest.java
Labels: BE, refactoring

#17 [후] 카드(할일) 도메인 개발
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
  backend/src/test/resources/data.sql
Labels: enhancement, BE

#23 [후] 카드(할일) 도메인 개발 리팩토링
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
Labels: BE, refactoring

#28 [Riako] MemberController 샘플 테스트 코드 작성
  backend/build.gradle
  backend/src/main/java/com/hooria/todo/config/WebMvcConfig.java
  backend/src/main/java/com/hooria/todo/controller/ActivityLogController.java
  backend/src/main/java/com/hooria/todo/controller/MemberController.java
  backend/src/main/java/com/hooria/todo/domain/ActivityLog.java
  backend/src/main/java/com/hooria/todo/domain/Member.java
  backend/src/main/java/com/hooria/todo/interceptor/EncodingInterceptor.java
  backend/src/main/java/com/hooria/todo/service/ActivityLogService.java
  backend/src/main/java/com/hooria/todo/service/MemberService.java
  backend/src/test/java/com/hooria/todo/controller/ActivityLogControllerMockTest.java
  backend/src/test/java/com/hooria/todo/controller/MemberControllerMockTest.java
  backend/src/test/java/com/hooria/todo/repository/ActivityLogRepositoryTest.java
  backend/src/test/java/com/hooria/todo/repository/MemberRepositoryTest.java
Labels: enhancement, BE

#30 [후] 카드(할 일) 도메인 변경사항 반영
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/domain/Device.java
  backend/src/main/java/com/hooria/todo/domain/Status.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
  backend/src/test/resources/data.sql
  backend/src/test/resources/schema.sql
Labels: enhancement, BE

#35 [#016] PR 올린 후 간단한 코드 정리
  backend/build.gradle
  backend/src/main/java/com/hooria/todo/controller/ActivityLogController.java
  backend/src/main/java/com/hooria/todo/domain/ActivityLog.java
  backend/src/main/java/com/hooria/todo/dto/ActivityLogsResponse.java
  backend/src/test/java/com/hooria/todo/controller/ActivityLogControllerMockTest.java
  backend/src/test/java/com/hooria/todo/controller/MemberControllerMockTest.java
Labels: BE

#36 [후] Card 비즈니스 로직(전체 조회, 신규 등록) 구현
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/domain/Device.java
  backend/src/main/java/com/hooria/todo/domain/Status.java
  backend/src/main/java/com/hooria/todo/dto/AddCardParam.java
  backend/src/main/java/com/hooria/todo/dto/CardResponse.java
  backend/src/main/java/com/hooria/todo/service/CardService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/hooria/todo/controller/CardControllerMockTest.java
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
  backend/src/test/resources/data.sql
Labels: enhancement, BE

#47 [후] Card 비즈니스 로직(삭제) 구현
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/java/com/hooria/todo/service/CardService.java
  backend/src/test/java/com/hooria/todo/controller/CardControllerMockTest.java
Labels: enhancement, BE

#48 [Riako] ActivityLog Mvc 구조 구체화 작업
  backend/src/main/java/com/hooria/todo/controller/ActionLogController.java
  backend/src/main/java/com/hooria/todo/dto/ActionLogResponse.java
  backend/src/main/java/com/hooria/todo/repository/ActionLogRepository.java
  backend/src/main/java/com/hooria/todo/service/ActionLogService.java
  backend/src/main/resources/dev/data.sql
  backend/src/main/resources/dev/schema.sql
  backend/src/main/resources/prod/schema.sql
  backend/src/test/java/com/hooria/todo/controller/ActionLogControllerMockTest.java
  backend/src/test/java/com/hooria/todo/controller/MemberControllerMockTest.java
  backend/src/test/java/com/hooria/todo/repository/ActionLogRepositoryTest.java
Labels: enhancement, BE

#52 [후] Card 비즈니스 로직(수정) 구현
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/dto/UpdateCardLayoutParam.java
  backend/src/main/java/com/hooria/todo/dto/UpdateCardParam.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/java/com/hooria/todo/service/CardService.java
  backend/src/test/java/com/hooria/todo/controller/CardControllerMockTest.java
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
Labels: enhancement, BE

#51 [Riako] 활동기록을 남기기 위한 AOP 적용 & 후와 협력
  backend/src/main/java/com/hooria/todo/aop/ActivityAspect.java
  backend/src/main/java/com/hooria/todo/aop/ExcludeLogging.java
  backend/src/main/java/com/hooria/todo/config/WebMvcConfig.java
  backend/src/main/java/com/hooria/todo/interceptor/AuthInterceptor.java
  backend/src/main/java/com/hooria/todo/service/ActivityLogService.java
  backend/src/main/java/com/hooria/todo/service/CardService.java
  backend/src/main/java/com/hooria/todo/session/SessionUser.java
Labels: enhancement, BE
